name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: latest

      - uses: pnpm/action-setup@v5
        with:
          version: latest
          run_install: true

      - run: pnpm test

      - run: pnpm run type-coverage

      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
