name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true

      - run: pnpm test -- --coverage
        env:
          NODE_OPTIONS: --experimental-vm-modules

      - run: pnpm run type-coverage

      - uses: codecov/codecov-action@v4
